// Inventario de equipos disponibles - Sistemas de Fuerza Industrial
// incluye ficha tecnica (medidas, peso, motor, etc.) cuando esta disponible
const EQUIPOS = [
  {
    "tipo": "Generador",
    "marca": "Generac",
    "modelo": "PLY1200",
    "cap_valor": 1200.0,
    "cap_unidad": "KW",
    "voltaje": "480V",
    "frecuencia": "60hz",
    "traslado": "Remolque Tracto",
    "cambio_voltaje": true,
    "cambio_frecuencia": false,
    "economico": 25,
    "ficha": {
      "motor_marca": "PERKINS",
      "motor_modelo": "4012-46TA",
      "motor_serie": "G1AEIPAK",
      "generador_marca": "LEROY SOMER",
      "generador_modelo": "LSA50. 2L8J6514",
      "combustible_lts": 2656.0,
      "anticongelante_lts": 350.0,
      "aceite_lts": 114.0,
      "dimensiones_caseta": "LARGO 792CM, ANCHO 240CM  ALTO 327CM",
      "peso_kg": 17000.0,
      "cantidad_ejes": 2.0,
      "modelo_llanta": "235/75R17",
      "amp_max": 1800.0,
      "selector_volt": "440 UNICAMENTE",
      "n_serie_equipo": "3013865971",
      "horometro": 202.16,
      "observaciones": "PLANTA CON REMOLQUE CAMA BAJA 8 LLANTAS"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Cummins Onan",
    "modelo": "1000DFJD",
    "cap_valor": 1000.0,
    "cap_unidad": "KW",
    "voltaje": "480V",
    "frecuencia": "60Hz",
    "traslado": "Remolque Tracto",
    "cambio_voltaje": false,
    "cambio_frecuencia": false,
    "economico": 28,
    "ficha": {
      "motor_marca": "CUMMINS",
      "motor_modelo": "KTA38G4",
      "motor_serie": "33118959",
      "generador_marca": "AC GENERATOR",
      "generador_modelo": "HC734E1",
      "combustible_lts": 4000.0,
      "anticongelante_lts": 350.0,
      "aceite_lts": 140.0,
      "dimensiones_caseta": "CONTENEDOR LARGO12.20MTS , ANCHO 2.45 , ALTO3MTS",
      "cantidad_ejes": 2.0,
      "modelo_llanta": "TRIANGLE 295/7522.5",
      "amp_max": 1500.0,
      "selector_volt": "480",
      "n_serie_equipo": "K940561368",
      "horometro": 2291.0
    }
  },
  {
    "tipo": "Generador",
    "marca": "Endress",
    "modelo": "ESE560",
    "cap_valor": 500.0,
    "cap_unidad": "KW",
    "voltaje": "440V",
    "frecuencia": "60Hz",
    "traslado": "Grua",
    "cambio_voltaje": true,
    "cambio_frecuencia": false,
    "economico": 30,
    "ficha": {
      "combustible_lts": 600.0
    }
  },
  {
    "tipo": "Generador",
    "marca": "Generac",
    "modelo": "GMM-590",
    "cap_valor": 500.0,
    "cap_unidad": "KW",
    "voltaje": "480V",
    "frecuencia": "60Hz",
    "traslado": "Remolqur",
    "cambio_voltaje": true,
    "cambio_frecuencia": false,
    "economico": 58,
    "ficha": {
      "motor_marca": "VOLVO",
      "motor_modelo": "TAD1641GR-B",
      "motor_serie": "2016182759",
      "generador_marca": "MECCALTE",
      "generador_modelo": "ECO401L4",
      "combustible_lts": 2300.0,
      "anticongelante_lts": 93.0,
      "aceite_lts": 48.0,
      "dimensiones_caseta": "ALTO: 285CM , LARGO:  430 CM , ANCHO: 160CM",
      "peso_kg": 6500.0,
      "cantidad_ejes": 3.0,
      "modelo_llanta": "ST235/80R16",
      "amp_max": 1714.0,
      "selector_volt": "MANUAL",
      "n_serie_equipo": "HEI0010998",
      "horometro": 2.7,
      "observaciones": "GENERADOR CON TANQUE GRANDE MOTOR VOLVO"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Generac",
    "modelo": "S590",
    "cap_valor": 500.0,
    "cap_unidad": "KW",
    "voltaje": "480V",
    "frecuencia": "60Hz",
    "traslado": "Grua",
    "cambio_voltaje": true,
    "cambio_frecuencia": false,
    "economico": 60,
    "ficha": {
      "motor_marca": "VOLVO",
      "motor_modelo": "TAD1641GE-B",
      "motor_serie": "2016182989",
      "peso_kg": 5800.0,
      "n_serie_equipo": "HEI0010999"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Endress",
    "modelo": "ESE5060LW/AS",
    "cap_valor": 454.0,
    "cap_unidad": "KW",
    "voltaje": "MANUAL",
    "frecuencia": "60Hz",
    "traslado": "remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": false,
    "economico": 80,
    "ficha": {
      "motor_marca": "CUMMINS",
      "motor_modelo": "KTA19-G3A",
      "motor_serie": "41367438",
      "generador_marca": "MECCALTE",
      "generador_modelo": "ECO401L4",
      "combustible_lts": 900.0,
      "anticongelante_lts": 90.0,
      "aceite_lts": 55.0,
      "dimensiones_caseta": "ALTO210CM, ANCHO170, LARGO450CM",
      "cantidad_ejes": 2.0,
      "modelo_llanta": "2215/75R17",
      "amp_max": 1490.0,
      "selector_volt": "MANUAL",
      "n_serie_equipo": "89331080-0008",
      "horometro": 0.0,
      "observaciones": "PLANTA ENDRESS NUEVA MONTADA EN REMOLQUE USADO"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Endress",
    "modelo": "ESE560",
    "cap_valor": 440.0,
    "cap_unidad": "KW",
    "voltaje": "220V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": true,
    "economico": 27,
    "ficha": {
      "motor_marca": "CUMMINS",
      "motor_modelo": "KTA19-G3A",
      "motor_serie": "41359527",
      "generador_marca": "MECCALTE",
      "generador_modelo": "ECO401L4",
      "combustible_lts": 900.0,
      "anticongelante_lts": 200.0,
      "aceite_lts": 38.0,
      "ancho_remolque": 235.0,
      "alto_remolque": 92.0,
      "dimensiones_caseta": "LARGO 400CM, ALTO210CM, ANCHO170CM",
      "peso_kg": 6000.0,
      "cantidad_ejes": 3.0,
      "modelo_llanta": "ST35/80R16",
      "amp_max": 1491.0,
      "selector_volt": "MANUAL",
      "n_serie_equipo": "333352/0004",
      "horometro": 460.0
    }
  },
  {
    "tipo": "Generador",
    "marca": "Cummins",
    "modelo": "300DFCB",
    "cap_valor": 300.0,
    "cap_unidad": "KW",
    "voltaje": "440V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": true,
    "economico": 5,
    "ficha": {
      "motor_marca": "CUMMINS",
      "motor_modelo": "NTA855G2",
      "motor_serie": "30342936",
      "generador_marca": "STAMFORD",
      "combustible_lts": 700.0,
      "anticongelante_lts": 60.0,
      "aceite_lts": 60.0,
      "dimensiones_caseta": "ALTO DE CASETA 200CM",
      "peso_kg": 3500.0,
      "cantidad_ejes": 2.0,
      "modelo_llanta": "7.50-16LT",
      "amp_max": 900.0,
      "selector_volt": "MANUAL",
      "n_serie_equipo": "L930527193",
      "observaciones": "PLANTA AZUL CUMMINS NTA"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Generac",
    "modelo": "PLY300",
    "cap_valor": 300.0,
    "cap_unidad": "KW",
    "voltaje": "MANUAL",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": false,
    "economico": 20,
    "ficha": {
      "motor_marca": "PERKINS",
      "motor_modelo": "1506A-E88TA65",
      "motor_serie": "16FF1026N18913I",
      "generador_marca": "STAMFORD",
      "generador_modelo": "54L1D-D41",
      "combustible_lts": 740.0,
      "anticongelante_lts": 75.0,
      "aceite_lts": 45.0,
      "dimensiones_caseta": "LARGO 400cm, ANCHO 146cm ,  ALTO 210cm",
      "cantidad_ejes": 2.0,
      "modelo_llanta": "st255/80R16",
      "amp_max": 986.0,
      "selector_volt": "MANUAL",
      "n_serie_equipo": "3013896741",
      "horometro": 678.3
    }
  },
  {
    "tipo": "Generador",
    "marca": "Generac",
    "modelo": "PLY300",
    "cap_valor": 300.0,
    "cap_unidad": "KW",
    "voltaje": "220V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": false,
    "economico": 20,
    "ficha": {
      "motor_marca": "PERKINS",
      "motor_modelo": "1506A-E88TA65",
      "motor_serie": "16FF1026N18913I",
      "generador_marca": "STAMFORD",
      "generador_modelo": "54L1D-D41",
      "combustible_lts": 740.0,
      "anticongelante_lts": 75.0,
      "aceite_lts": 45.0,
      "dimensiones_caseta": "LARGO 400cm, ANCHO 146cm ,  ALTO 210cm",
      "cantidad_ejes": 2.0,
      "modelo_llanta": "st255/80R16",
      "amp_max": 986.0,
      "selector_volt": "MANUAL",
      "n_serie_equipo": "3013896741",
      "horometro": 678.3
    }
  },
  {
    "tipo": "Generador",
    "marca": "Otomotores",
    "modelo": null,
    "cap_valor": 250.0,
    "cap_unidad": "KW",
    "voltaje": "220V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": true,
    "economico": 4,
    "ficha": {
      "motor_marca": "CUMMINS",
      "motor_modelo": "LTA10G1",
      "combustible_lts": 650.0,
      "anticongelante_lts": 75.0,
      "aceite_lts": 38.0,
      "dimensiones_caseta": "LARGO 457CM ANCHO 143CM    ALTO190CM",
      "peso_kg": 3500.0,
      "cantidad_ejes": 2.0,
      "modelo_llanta": "ST235/80R16",
      "amp_max": 750.0,
      "selector_volt": "MANUAL",
      "horometro": 3166.0,
      "observaciones": "PLANTA AZUL CUMMINS LTA10G1"
    }
  },
  {
    "tipo": "Generador",
    "marca": "MQ",
    "modelo": "MQP240",
    "cap_valor": 240.0,
    "cap_unidad": "KW",
    "voltaje": "220/440V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": false,
    "economico": 70,
    "ficha": {
      "motor_marca": "CUMMINS",
      "motor_modelo": "QSL9-G3",
      "motor_serie": "EE56548",
      "generador_marca": "BRUSHELSS",
      "generador_modelo": "DF 3300C",
      "anticongelante_lts": 43.0,
      "aceite_lts": 27.0,
      "dimensiones_caseta": "ALTO 181CM, ANCHO 140CM, LARGO 380CM",
      "peso_kg": 4500.0,
      "cantidad_ejes": 2.0,
      "modelo_llanta": "235/75R17.5",
      "amp_max": 700.0,
      "selector_volt": "220/440",
      "horometro": 12597.0,
      "observaciones": "EQUIPO CON MOTOR ROTO"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Generac",
    "modelo": "PLY200",
    "cap_valor": 200.0,
    "cap_unidad": "KW",
    "voltaje": "MANUAL",
    "frecuencia": "60Hz",
    "traslado": "REMOLQUE",
    "cambio_voltaje": false,
    "cambio_frecuencia": false,
    "economico": 87,
    "ficha": {
      "motor_marca": "PERKINS",
      "motor_modelo": "1106D-E70TA",
      "motor_serie": "PW83059B629547L",
      "generador_marca": "LEROY-SOMER",
      "generador_modelo": "TAL-A44-M M 6/4",
      "dimensiones_caseta": "ANCHO: 1.45MTS, ALTO: 1.70, LARGO: 3.41MTS",
      "modelo_llanta": "215/75/R17.5",
      "selector_volt": "MANUAL",
      "n_serie_equipo": "3018515217",
      "horometro": 0.0,
      "observaciones": "GENERADOR GENERAC NUEVO, MONTADO EN REMOLQUE 2 EJES USADO"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Generac",
    "modelo": "PLY180",
    "cap_valor": 180.0,
    "cap_unidad": "KW",
    "voltaje": "480V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": false,
    "economico": 8,
    "ficha": {
      "motor_marca": "PERKINS",
      "motor_serie": "PW83059*R031425G",
      "generador_marca": "LEROY SOMAR",
      "combustible_lts": 540.0,
      "anticongelante_lts": 40.0,
      "aceite_lts": 19.0,
      "alto_remolque": 71.0,
      "dimensiones_caseta": "310 CM",
      "peso_kg": 3000.0,
      "cantidad_ejes": 2.0,
      "modelo_llanta": "ST205/75/15",
      "selector_volt": "MANUAL",
      "horometro": 8398.53,
      "observaciones": "PLANTA AZUL MOTOR PERKINS"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Aggreko",
    "modelo": "Equipos importados",
    "cap_valor": 150.0,
    "cap_unidad": "KW",
    "voltaje": "220V",
    "frecuencia": "60Hz",
    "traslado": "REMOLQUE",
    "cambio_voltaje": false,
    "cambio_frecuencia": false,
    "economico": 47,
    "ficha": {
      "motor_marca": "CUMMINS",
      "motor_modelo": "QSB7-G6 NR4",
      "motor_serie": "22029081",
      "generador_marca": "STAMFORD",
      "generador_modelo": "VCD1274J1",
      "combustible_lts": 950.0,
      "anticongelante_lts": 16.0,
      "aceite_lts": 19.0,
      "dimensiones_caseta": "LARGO: 420CM, ANCHO: 120CM, ALTO: 230CM",
      "peso_kg": 5000.0,
      "amp_max": 600.0,
      "selector_volt": "220/440",
      "n_serie_equipo": "10009766-01",
      "horometro": 15287.0,
      "observaciones": "EQUIPO EN REPARACION"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Endress",
    "modelo": "ESE190",
    "cap_valor": 136.0,
    "cap_unidad": "KW",
    "voltaje": "220V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": true,
    "economico": 11,
    "ficha": {
      "motor_marca": "CUMMINS",
      "motor_modelo": "6BTAA5.9G12",
      "motor_serie": "82434517",
      "generador_marca": "MECCALTE",
      "generador_modelo": "ECP34 2L4",
      "combustible_lts": 650.0,
      "anticongelante_lts": 20.0,
      "aceite_lts": 19.0,
      "dimensiones_caseta": "LARGO 290CM, ANCHO110CM, ALTO 185CM",
      "peso_kg": 3200.0,
      "cantidad_ejes": 2.0,
      "modelo_llanta": "ST235/80/R16",
      "amp_max": 425.0,
      "selector_volt": "MANUAL",
      "horometro": 2663.14,
      "observaciones": "24/09/2025 se instala remolque nuevo fabricado en patio"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Endress",
    "modelo": "ESE190",
    "cap_valor": 136.0,
    "cap_unidad": "KW",
    "voltaje": "440V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": true,
    "economico": 11,
    "ficha": {
      "motor_marca": "CUMMINS",
      "motor_modelo": "6BTAA5.9G12",
      "motor_serie": "82434517",
      "generador_marca": "MECCALTE",
      "generador_modelo": "ECP34 2L4",
      "combustible_lts": 650.0,
      "anticongelante_lts": 20.0,
      "aceite_lts": 19.0,
      "dimensiones_caseta": "LARGO 290CM, ANCHO110CM, ALTO 185CM",
      "peso_kg": 3200.0,
      "cantidad_ejes": 2.0,
      "modelo_llanta": "ST235/80/R16",
      "amp_max": 425.0,
      "selector_volt": "MANUAL",
      "horometro": 2663.14,
      "observaciones": "24/09/2025 se instala remolque nuevo fabricado en patio"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Endress",
    "modelo": "ES190CW/AS",
    "cap_valor": 136.0,
    "cap_unidad": "KW",
    "voltaje": "480V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": true,
    "economico": 10,
    "ficha": {
      "motor_marca": "CUMMINS",
      "motor_modelo": "6BTAA 5.9G12",
      "motor_serie": "82190511",
      "generador_marca": "MECCALTE",
      "generador_modelo": "TYPE ECP342L4",
      "combustible_lts": 650.0,
      "anticongelante_lts": 20.0,
      "aceite_lts": 19.0,
      "dimensiones_caseta": "LARGO 291cm, ANCHO 109cm, ALTO 190cm",
      "cantidad_ejes": 2.0,
      "modelo_llanta": "ST235/80R16",
      "selector_volt": "MANUAL",
      "n_serie_equipo": "333333/0026",
      "horometro": 14568.22,
      "observaciones": "1 METRO DE MANGUERA 3/8 PARA RETORNO DE DIESEL, 30 CM MANGUERA 3/8 ALIMENTACION DE DIESEL, 70 MANGUERA A 1/2"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Caterpillar",
    "modelo": null,
    "cap_valor": 125.0,
    "cap_unidad": "KW",
    "voltaje": "440V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": false,
    "economico": 6,
    "ficha": {
      "motor_marca": "CATERPILLAR",
      "motor_modelo": "3406 C",
      "generador_marca": "CAT",
      "generador_modelo": "SR4B",
      "combustible_lts": 800.0,
      "anticongelante_lts": 60.0,
      "aceite_lts": 35.0,
      "dimensiones_caseta": "ALTO 205 CM, ANCHO 161CM LARGO450CM",
      "peso_kg": 3500.0,
      "cantidad_ejes": 2.0,
      "modelo_llanta": "7.50-16LTR16",
      "amp_max": 390.0,
      "selector_volt": "MANUAL",
      "horometro": 1831.28,
      "observaciones": "PLANTA AZUL CAT"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Otomotores",
    "modelo": null,
    "cap_valor": 120.0,
    "cap_unidad": "KW",
    "voltaje": "220V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": true,
    "economico": 3,
    "ficha": {
      "motor_marca": "CUMMINS",
      "motor_modelo": "6CTA",
      "combustible_lts": 440.0,
      "anticongelante_lts": 40.0,
      "aceite_lts": 20.0,
      "dimensiones_caseta": "LARGO 390CM, ANCHO100 CM, ALTO 182CM",
      "peso_kg": 3000.0,
      "cantidad_ejes": 2.0,
      "modelo_llanta": "7.00-1SLT",
      "amp_max": 360.0,
      "selector_volt": "MANUAL",
      "horometro": 1435.15,
      "observaciones": "PLANTA AZUL CUMMINS 6BT"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Kohler",
    "modelo": null,
    "cap_valor": 100.0,
    "cap_unidad": "KW",
    "voltaje": "480V",
    "frecuencia": "60Hz",
    "traslado": "Grúa",
    "cambio_voltaje": true,
    "cambio_frecuencia": false
  },
  {
    "tipo": "Generador",
    "marca": "Endress",
    "modelo": "ESE125",
    "cap_valor": 100.0,
    "cap_unidad": "KW",
    "voltaje": "480V",
    "frecuencia": "60Hz",
    "traslado": "Grua",
    "cambio_voltaje": true,
    "cambio_frecuencia": true
  },
  {
    "tipo": "Generador",
    "marca": "Generac",
    "modelo": "GMM115P/SNE",
    "cap_valor": 100.0,
    "cap_unidad": "KW",
    "voltaje": "220V",
    "frecuencia": "60Hz",
    "traslado": "Grúa",
    "cambio_voltaje": true,
    "cambio_frecuencia": true,
    "economico": 45,
    "ficha": {
      "motor_marca": "PERKINS",
      "motor_modelo": "1104C-44TA",
      "motor_serie": "RJ51175*U748446K*",
      "generador_marca": "MECCALTE",
      "generador_modelo": "ECP34 254C",
      "combustible_lts": 350.0,
      "anticongelante_lts": 13.0,
      "aceite_lts": 8.0,
      "dimensiones_caseta": "LARGO 276cm , ANCHO 113CM, ALTO190CM",
      "amp_max": 308.0,
      "selector_volt": "220",
      "n_serie_equipo": "PEE2695677",
      "horometro": 0.24,
      "observaciones": "REGULADOR DE VOLTAJE MECCALTE MOD. DSR/A6762/07"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Modasa",
    "modelo": "X32054F",
    "cap_valor": 100.0,
    "cap_unidad": "KW",
    "voltaje": "220V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": true,
    "economico": 17,
    "ficha": {
      "motor_marca": "CUMMINS",
      "motor_modelo": "6BT5.9-G2",
      "motor_serie": "82390570",
      "generador_marca": "MODASA",
      "generador_modelo": "LYG2745",
      "combustible_lts": 250.0,
      "anticongelante_lts": 25.0,
      "aceite_lts": 19.0,
      "dimensiones_caseta": "LARGO 260CM, ANCHO 105CM. ALTO163CM",
      "peso_kg": 2500.0,
      "cantidad_ejes": 2.0,
      "modelo_llanta": "ST205/75R14",
      "amp_max": 300.0,
      "selector_volt": "MANUAL",
      "n_serie_equipo": "X32054F",
      "horometro": 3944.0
    }
  },
  {
    "tipo": "Generador",
    "marca": "Perkins",
    "modelo": "Perkins",
    "cap_valor": 100.0,
    "cap_unidad": "KW",
    "voltaje": "220V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": true,
    "economico": 19,
    "ficha": {
      "motor_marca": "PERKINS",
      "motor_modelo": "110AC-44TA",
      "motor_serie": "RJ51338B607876J",
      "generador_marca": "STAMFORD",
      "generador_modelo": "UCI2740",
      "combustible_lts": 400.0,
      "anticongelante_lts": 19.0,
      "aceite_lts": 8.0,
      "dimensiones_caseta": "LARGO 285cm, ANCHO 122cm, ALTO 180cm",
      "cantidad_ejes": 2.0,
      "modelo_llanta": "ST205/75D15",
      "amp_max": 164.0,
      "selector_volt": "MANUAL",
      "n_serie_equipo": "RJS1338B607876J",
      "horometro": 3224.4,
      "observaciones": "1PZ RECALENTADOR 1000W-127V, MANGUERA DE RETORNO DEL DIESEL 5/16, MANGUERA INYECCION DIESEL 3/8, REGULADOR DE VOLTAJE STAMFORD MOD:AS440UL/E000-24408 *SIN REMOLQUE*"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Ingersoll Rand",
    "modelo": "G/25",
    "cap_valor": 100.0,
    "cap_unidad": "KW",
    "voltaje": "440V",
    "frecuencia": "60Hz",
    "traslado": "remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": false,
    "economico": 78,
    "ficha": {
      "motor_marca": "J DEERE",
      "motor_modelo": "6068TF275",
      "motor_serie": "PE6068T660607",
      "combustible_lts": 600.0,
      "anticongelante_lts": 20.0,
      "aceite_lts": 20.0,
      "dimensiones_caseta": "ALTO 420CM ,ANCHO 185CM, ALTO TOTAL CON CASETA Y REMOLQUE 190CM",
      "peso_kg": 3000.0,
      "cantidad_ejes": 2.0,
      "modelo_llanta": "ST205/75R15",
      "amp_max": 300.0,
      "selector_volt": "220/440",
      "n_serie_equipo": "3908",
      "horometro": 10858.0,
      "observaciones": "PLANTA 100KW INGERSSOL"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Endress",
    "modelo": null,
    "cap_valor": 80.0,
    "cap_unidad": "KW",
    "voltaje": "480V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": false,
    "economico": 16,
    "ficha": {
      "motor_marca": "PERKINS",
      "motor_modelo": "1104A-44T",
      "motor_serie": "RS51277*U724204H*",
      "generador_marca": "MECALTE",
      "generador_modelo": "ECP322L4",
      "combustible_lts": 220.0,
      "anticongelante_lts": 20.0,
      "aceite_lts": 13.0,
      "largo_remolque": 480.0,
      "ancho_remolque": 185.0,
      "alto_remolque": 75.0,
      "dimensiones_caseta": "LARGO DE CASETA :480CM , ANCHO DE CASETA 100CM , ALTO DE CASETA: 175 CM",
      "peso_kg": 2800.0,
      "cantidad_ejes": 2.0,
      "modelo_llanta": "ST 205/75 R14",
      "amp_max": 262.0,
      "selector_volt": "MANUAL",
      "n_serie_equipo": "PEE2686587",
      "horometro": 4392.0,
      "observaciones": "TIRON DE DONA"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Endress",
    "modelo": "ESE65",
    "cap_valor": 60.0,
    "cap_unidad": "KW",
    "voltaje": "220V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": true,
    "economico": 14,
    "ficha": {
      "motor_marca": "PERKINS",
      "motor_modelo": "1103A-33TG2",
      "motor_serie": "U608568H",
      "generador_marca": "MECCALTE",
      "generador_modelo": "ECP322M4C",
      "combustible_lts": 100.0,
      "anticongelante_lts": 20.0,
      "aceite_lts": 15.0,
      "dimensiones_caseta": "220cmlargo, 100cm ancho, 122cm alto",
      "cantidad_ejes": 2.0,
      "modelo_llanta": "ST7.00-15",
      "selector_volt": "MANUAL",
      "n_serie_equipo": "PEE268417",
      "horometro": 2900.36,
      "observaciones": "EQUIPO CUENTA CON RASTROS DE PINTURA BLANCA EN SU EXTERIOR, EQUIPO OPERANDO CORRECTAMENTE"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Generac",
    "modelo": "PLY60",
    "cap_valor": 60.0,
    "cap_unidad": "KW",
    "voltaje": "220V",
    "frecuencia": "60Hz",
    "traslado": "Grúa",
    "cambio_voltaje": true,
    "cambio_frecuencia": true,
    "economico": 31,
    "ficha": {
      "motor_marca": "PERKINS",
      "motor_modelo": "1103A-33T",
      "motor_serie": "DK32000B618060K",
      "generador_marca": "LEROY SOMEER",
      "generador_modelo": "TAL042H J6/4",
      "combustible_lts": 150.0,
      "anticongelante_lts": 19.0,
      "aceite_lts": 10.0,
      "dimensiones_caseta": "ALTO 146CM, ANCHO110CM, LARGO230CM",
      "peso_kg": 1200.0,
      "amp_max": 197.0,
      "selector_volt": "220/440",
      "n_serie_equipo": "3015248627",
      "horometro": 916.38
    }
  },
  {
    "tipo": "Generador",
    "marca": "Generac",
    "modelo": "GMM70P/SNE",
    "cap_valor": 60.0,
    "cap_unidad": "KW",
    "voltaje": "220V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": true,
    "economico": 43,
    "ficha": {
      "motor_marca": "PERKINS",
      "motor_modelo": "1103A-33TG2",
      "motor_serie": "DK32000U627620K",
      "generador_marca": "MECCALTE",
      "generador_modelo": "ECP32 2M4C",
      "combustible_lts": 80.0,
      "anticongelante_lts": 12.0,
      "aceite_lts": 9.0,
      "dimensiones_caseta": "LARGO 220cm,ANCHO 100cm, ALTO 150cm",
      "amp_max": 197.0,
      "selector_volt": "220",
      "n_serie_equipo": "PEE2695544",
      "horometro": 8.4,
      "observaciones": "REGULADOR DE VOLTAJE MECCALTE MOD. DSR/A6762/07"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Generac",
    "modelo": "GMM70P/SNE",
    "cap_valor": 60.0,
    "cap_unidad": "KW",
    "voltaje": "440V",
    "frecuencia": "60Hz",
    "traslado": "Grua",
    "cambio_voltaje": true,
    "cambio_frecuencia": true,
    "economico": 43,
    "ficha": {
      "motor_marca": "PERKINS",
      "motor_modelo": "1103A-33TG2",
      "motor_serie": "DK32000U627620K",
      "generador_marca": "MECCALTE",
      "generador_modelo": "ECP32 2M4C",
      "combustible_lts": 80.0,
      "anticongelante_lts": 12.0,
      "aceite_lts": 9.0,
      "dimensiones_caseta": "LARGO 220cm,ANCHO 100cm, ALTO 150cm",
      "amp_max": 197.0,
      "selector_volt": "220",
      "n_serie_equipo": "PEE2695544",
      "horometro": 8.4,
      "observaciones": "REGULADOR DE VOLTAJE MECCALTE MOD. DSR/A6762/07"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Generac",
    "modelo": "GMM70P/SNE",
    "cap_valor": 60.0,
    "cap_unidad": "KW",
    "voltaje": "220V",
    "frecuencia": "60Hz",
    "traslado": "Grua",
    "cambio_voltaje": true,
    "cambio_frecuencia": true,
    "economico": 43,
    "ficha": {
      "motor_marca": "PERKINS",
      "motor_modelo": "1103A-33TG2",
      "motor_serie": "DK32000U627620K",
      "generador_marca": "MECCALTE",
      "generador_modelo": "ECP32 2M4C",
      "combustible_lts": 80.0,
      "anticongelante_lts": 12.0,
      "aceite_lts": 9.0,
      "dimensiones_caseta": "LARGO 220cm,ANCHO 100cm, ALTO 150cm",
      "amp_max": 197.0,
      "selector_volt": "220",
      "n_serie_equipo": "PEE2695544",
      "horometro": 8.4,
      "observaciones": "REGULADOR DE VOLTAJE MECCALTE MOD. DSR/A6762/07"
    }
  },
  {
    "tipo": "Generador",
    "marca": "MQ",
    "modelo": "DCA-4555IU4F",
    "cap_valor": 56.0,
    "cap_unidad": "KW",
    "voltaje": "220/440V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": false,
    "economico": 66,
    "ficha": {
      "motor_marca": "ISUZU",
      "motor_modelo": "BR-4JJ1X",
      "motor_serie": "4JJIXDRBB-01",
      "generador_marca": "BRUSHELESS",
      "generador_modelo": "DH 07501(T4)",
      "combustible_lts": 309.0,
      "anticongelante_lts": 12.0,
      "aceite_lts": 19.0,
      "dimensiones_caseta": "ALTO:175CM, ANCHO:95CM  LARGO:268CM",
      "peso_kg": 3000.0,
      "modelo_llanta": "ST205/75D15",
      "amp_max": 150.0,
      "selector_volt": "220/440",
      "n_serie_equipo": "7354278",
      "horometro": 18852.0,
      "observaciones": "EQUIPO EN REPARACION"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Olympian",
    "modelo": null,
    "cap_valor": 50.0,
    "cap_unidad": "KW",
    "voltaje": "440V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": true,
    "economico": 1,
    "ficha": {
      "motor_marca": "PERKINS",
      "generador_marca": "OLYMPIAN",
      "generador_modelo": "D50P1",
      "combustible_lts": 550.0,
      "anticongelante_lts": 25.0,
      "aceite_lts": 14.0,
      "dimensiones_caseta": "LARGO 230CM  ANCHO 109CMALTO 119CM",
      "peso_kg": 2000.0,
      "cantidad_ejes": 2.0,
      "modelo_llanta": "7.00-15LT",
      "amp_max": 150.0,
      "selector_volt": "MANUAL",
      "horometro": 450.0,
      "observaciones": "CASETA GRIS"
    }
  },
  {
    "tipo": "Generador",
    "marca": null,
    "modelo": null,
    "cap_valor": 50.0,
    "cap_unidad": "KW",
    "voltaje": "220V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": true,
    "economico": 2,
    "ficha": {
      "motor_marca": "CUMMINS",
      "motor_modelo": "4BT3.9G1",
      "motor_serie": "44775820",
      "generador_marca": "WEG",
      "combustible_lts": 350.0,
      "anticongelante_lts": 25.0,
      "aceite_lts": 19.0,
      "alto_remolque": 192.0,
      "dimensiones_caseta": "MISMAS",
      "peso_kg": 2800.0,
      "cantidad_ejes": 2.0,
      "modelo_llanta": "7.00-1SLT",
      "amp_max": 150.0,
      "selector_volt": "MANUAL",
      "horometro": 7946.0,
      "observaciones": "CASETA MONTADA FIJA EN REMOLQUE"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Magnum",
    "modelo": "MMG75D",
    "cap_valor": 50.0,
    "cap_unidad": "KW",
    "voltaje": "220V",
    "frecuencia": "60Hz",
    "traslado": "Grua",
    "cambio_voltaje": true,
    "cambio_frecuencia": false,
    "economico": 51,
    "ficha": {
      "motor_marca": "J.DEERE",
      "motor_modelo": "4045HFG92",
      "motor_serie": "PE4045R080963",
      "generador_marca": "MAGNAPLUS",
      "generador_modelo": "363NSL1661",
      "combustible_lts": 600.0,
      "anticongelante_lts": 12.0,
      "aceite_lts": 15.0,
      "dimensiones_caseta": "LARGO 300cm, ANCHO 102cm , ALTO 170cm",
      "cantidad_ejes": 2.0,
      "modelo_llanta": "ST205/175R15",
      "amp_max": 180.0,
      "selector_volt": "220/440",
      "n_serie_equipo": "1407193",
      "horometro": 9550.0,
      "observaciones": "GENERADOR MAGNUM USADO AMERICANO CON REMOLQUE"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Hipower",
    "modelo": "HRJW-115T6",
    "cap_valor": 50.0,
    "cap_unidad": "KW",
    "voltaje": "240V/440V",
    "frecuencia": "60Hz",
    "traslado": "Grua",
    "cambio_voltaje": true,
    "cambio_frecuencia": false,
    "economico": 62,
    "ficha": {
      "motor_marca": "JONHDEERE",
      "motor_modelo": "4045HF285",
      "motor_serie": "PE4045L182920",
      "generador_marca": "STAMFORD",
      "generador_modelo": "I001621/018",
      "combustible_lts": 800.0,
      "anticongelante_lts": 25.0,
      "aceite_lts": 19.0,
      "dimensiones_caseta": "ALTO 209, ANCHO115 , LARGO281",
      "peso_kg": 3000.0,
      "amp_max": 180.0,
      "selector_volt": "220/440",
      "horometro": 9576.0
    }
  },
  {
    "tipo": "Generador",
    "marca": "Godwin",
    "modelo": "GPH65KW-R",
    "cap_valor": 50.0,
    "cap_unidad": "KW",
    "voltaje": "220/440V",
    "frecuencia": "60Hz",
    "traslado": "remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": false,
    "economico": 73,
    "ficha": {
      "motor_marca": "J.DEERE",
      "motor_modelo": "4045TF275",
      "motor_serie": "PE4045T671802",
      "generador_marca": "MARATHON",
      "generador_modelo": "363 NSL 1661",
      "combustible_lts": 500.0,
      "anticongelante_lts": 25.0,
      "aceite_lts": 12.0,
      "dimensiones_caseta": "ALTO 98CM , ANCHO  98CM , LARGO 245CM",
      "peso_kg": 2000.0,
      "cantidad_ejes": 0.0,
      "amp_max": 180.0,
      "selector_volt": "220/440"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Godwin",
    "modelo": "GPH65KW-R",
    "cap_valor": 50.0,
    "cap_unidad": "KW",
    "voltaje": "220/440V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": false,
    "economico": 73,
    "ficha": {
      "motor_marca": "J.DEERE",
      "motor_modelo": "4045TF275",
      "motor_serie": "PE4045T671802",
      "generador_marca": "MARATHON",
      "generador_modelo": "363 NSL 1661",
      "combustible_lts": 500.0,
      "anticongelante_lts": 25.0,
      "aceite_lts": 12.0,
      "dimensiones_caseta": "ALTO 98CM , ANCHO  98CM , LARGO 245CM",
      "peso_kg": 2000.0,
      "cantidad_ejes": 0.0,
      "amp_max": 180.0,
      "selector_volt": "220/440"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Generac",
    "modelo": "GMM56P/SNE",
    "cap_valor": 40.0,
    "cap_unidad": "KW",
    "voltaje": "220V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": true,
    "economico": 39,
    "ficha": {
      "motor_marca": "PERKINS",
      "motor_modelo": "1103A-33TG1",
      "motor_serie": "U16167935",
      "generador_marca": "MECCALTE",
      "generador_modelo": "ECP32 254C",
      "combustible_lts": 80.0,
      "anticongelante_lts": 20.0,
      "aceite_lts": 13.0,
      "dimensiones_caseta": "LARGO 220cm,ANCHO 100cm, ALTO 150cm",
      "amp_max": 131.0,
      "selector_volt": "220",
      "n_serie_equipo": "PEE2695553",
      "horometro": 1.34,
      "observaciones": "FALTA FILTRO RACOR, NO VISIBLES LAS MEDIDAS EXACTAS DE MANGUERAS"
    }
  },
  {
    "tipo": "Generador",
    "marca": "MQ",
    "modelo": "DCA-4555IU4F",
    "cap_valor": 35.0,
    "cap_unidad": "KW",
    "voltaje": "220V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": false,
    "economico": 61,
    "ficha": {
      "motor_marca": "ISUZU",
      "motor_modelo": "4LE2X",
      "motor_serie": "4LC2-G54427",
      "generador_marca": "BRUSHELESS",
      "generador_modelo": "DH-04801",
      "combustible_lts": 300.0,
      "anticongelante_lts": 12.0,
      "aceite_lts": 14.0,
      "dimensiones_caseta": "ALTO   167 CM ,   ANCHO 95CM  ,    LARGO 213 CM",
      "peso_kg": 1200.0,
      "amp_max": 90.0,
      "selector_volt": "220/440",
      "n_serie_equipo": "7251802",
      "horometro": 13474.0,
      "observaciones": "MQ AZUL LLEGO CON REMOLQUE PERO SE LE RETIRO"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Endress",
    "modelo": "ESE40",
    "cap_valor": 30.0,
    "cap_unidad": "KW",
    "voltaje": "220V",
    "frecuencia": "60Hz",
    "traslado": "Grúa",
    "cambio_voltaje": false,
    "cambio_frecuencia": true,
    "economico": 23,
    "ficha": {
      "motor_marca": "PERKINS",
      "motor_modelo": "1103A-33G",
      "motor_serie": "DJ32003V6196075",
      "generador_marca": "MECCALTE",
      "generador_modelo": "ECP28VL4C",
      "combustible_lts": 80.0,
      "anticongelante_lts": 11.0,
      "aceite_lts": 9.0,
      "dimensiones_caseta": "LARGO 220CM, ANCHO 100CM, ALTO 135CM",
      "peso_kg": 1800.0,
      "amp_max": 98.0,
      "selector_volt": "MANUAL",
      "n_serie_equipo": "PEE2687576",
      "horometro": 6562.0,
      "observaciones": "EQUIPO NO CUENTA CON REMOLQUE"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Endress",
    "modelo": "ESE30",
    "cap_valor": 30.0,
    "cap_unidad": "KW",
    "voltaje": "220V",
    "frecuencia": "60Hz",
    "traslado": "Grúa",
    "cambio_voltaje": true,
    "cambio_frecuencia": true,
    "economico": 46,
    "ficha": {
      "motor_marca": "PERKINS",
      "motor_modelo": "1103A-33G",
      "motor_serie": "U614525J",
      "generador_marca": "MECCALTE",
      "generador_modelo": "P295244",
      "combustible_lts": 90.0,
      "anticongelante_lts": 20.0,
      "aceite_lts": 15.0,
      "dimensiones_caseta": "LARGO 220cm, ANCHO 100cm. ALTO 150cm",
      "amp_max": 78.0,
      "selector_volt": "220",
      "n_serie_equipo": "PEE2691890",
      "horometro": 0.54,
      "observaciones": "MANGUERAS DE ALIMENTACION 3/8RETORNO 5/16"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Endress",
    "modelo": "ISO828",
    "cap_valor": 30.0,
    "cap_unidad": "KW",
    "voltaje": "220V",
    "frecuencia": "60hz",
    "traslado": "Remolque",
    "cambio_voltaje": false,
    "cambio_frecuencia": false,
    "economico": 12,
    "ficha": {
      "motor_marca": "YANMAR",
      "motor_modelo": "4TNV98T-GGE",
      "motor_serie": "186034",
      "generador_marca": "MECCALTE",
      "generador_modelo": "TYPEEECP32254",
      "combustible_lts": 180.0,
      "dimensiones_caseta": "LARGO 225CM, ANCHO 96 CM, ALTO 140CM",
      "cantidad_ejes": 2.0,
      "modelo_llanta": "ST205/75/R14",
      "selector_volt": "MANUAL",
      "n_serie_equipo": "339271/0058",
      "horometro": 22714.4,
      "observaciones": "PLANTA CON REMOLQUE SE INSTALO EL 20/09/2025"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Wacker",
    "modelo": "G50",
    "cap_valor": 30.0,
    "cap_unidad": "KW",
    "voltaje": "12V",
    "frecuencia": "60Hz",
    "traslado": null,
    "cambio_voltaje": false,
    "cambio_frecuencia": false,
    "economico": 63,
    "ficha": {
      "motor_marca": "J. DEERE",
      "motor_modelo": "4045DF270D",
      "motor_serie": "PE4045D546635",
      "generador_marca": "MECCALTE",
      "generador_modelo": "ECO32-35/4",
      "combustible_lts": 300.0,
      "anticongelante_lts": 19.0,
      "aceite_lts": 19.0,
      "dimensiones_caseta": "ALTO 51CM, ANCHO 178CM, LARGO 400CM",
      "peso_kg": 2000.0,
      "cantidad_ejes": 1.0,
      "modelo_llanta": "ST 225/75R15",
      "amp_max": 90.0,
      "selector_volt": "220/440",
      "n_serie_equipo": "5640583"
    }
  },
  {
    "tipo": "Generador",
    "marca": "MQ",
    "modelo": "DCA-4555IU4F",
    "cap_valor": 30.0,
    "cap_unidad": "KW",
    "voltaje": "220V/480V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": false
  },
  {
    "tipo": "Generador",
    "marca": "Atlas Copco",
    "modelo": "25KVA",
    "cap_valor": 20.0,
    "cap_unidad": "KW",
    "voltaje": "220V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": false,
    "cambio_frecuencia": false,
    "economico": 59,
    "ficha": {
      "motor_marca": "ISUZU",
      "motor_modelo": "4LE2TDZBA-01",
      "motor_serie": "4LE2-652310",
      "generador_marca": "ESTAMFORD",
      "combustible_lts": 270.0,
      "anticongelante_lts": 15.0,
      "aceite_lts": 12.0,
      "alto_remolque": 76.0,
      "dimensiones_caseta": "ALTO 128CM, LARGO182CM ANCHO84CM",
      "peso_kg": 1200.0,
      "cantidad_ejes": 1.0,
      "modelo_llanta": "ST175/80/13",
      "amp_max": 60.0,
      "selector_volt": "220/440",
      "n_serie_equipo": "HOP 121153",
      "horometro": 10195.42,
      "observaciones": "ATLAS COPCO"
    }
  },
  {
    "tipo": "Generador",
    "marca": "MQ",
    "modelo": "DCA-25SSIU4F",
    "cap_valor": 20.0,
    "cap_unidad": "KW",
    "voltaje": "220/440V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": false,
    "economico": 65,
    "ficha": {
      "motor_marca": "ISUZU",
      "motor_modelo": "BZ-4LE2T",
      "motor_serie": "4LE2-689472",
      "generador_marca": "BRUSHELESS",
      "generador_modelo": "DF-027012",
      "combustible_lts": 150.0,
      "anticongelante_lts": 13.0,
      "aceite_lts": 12.0,
      "largo_remolque": 285.0,
      "ancho_remolque": 150.0,
      "alto_remolque": 30.0,
      "dimensiones_caseta": "ALTO 123CM , ANCHO 82CM, LARGO 187",
      "peso_kg": 800.0,
      "cantidad_ejes": 1.0,
      "modelo_llanta": "ST 175-80DTS R13",
      "selector_volt": "220/440",
      "n_serie_equipo": "7155874",
      "horometro": 7564.3,
      "observaciones": "EQUIPO EN REPARACION"
    }
  },
  {
    "tipo": "Generador",
    "marca": "MQ",
    "modelo": "DCA-25SSIU4F",
    "cap_valor": 20.0,
    "cap_unidad": "KW",
    "voltaje": "220/440V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": false,
    "economico": 65,
    "ficha": {
      "motor_marca": "ISUZU",
      "motor_modelo": "BZ-4LE2T",
      "motor_serie": "4LE2-689472",
      "generador_marca": "BRUSHELESS",
      "generador_modelo": "DF-027012",
      "combustible_lts": 150.0,
      "anticongelante_lts": 13.0,
      "aceite_lts": 12.0,
      "largo_remolque": 285.0,
      "ancho_remolque": 150.0,
      "alto_remolque": 30.0,
      "dimensiones_caseta": "ALTO 123CM , ANCHO 82CM, LARGO 187",
      "peso_kg": 800.0,
      "cantidad_ejes": 1.0,
      "modelo_llanta": "ST 175-80DTS R13",
      "selector_volt": "220/440",
      "n_serie_equipo": "7155874",
      "horometro": 7564.3,
      "observaciones": "EQUIPO EN REPARACION"
    }
  },
  {
    "tipo": "Generador",
    "marca": "Endress",
    "modelo": "ESE25 YW-B",
    "cap_valor": 18.0,
    "cap_unidad": "KW",
    "voltaje": "220V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": true,
    "economico": 13,
    "ficha": {
      "motor_marca": "YANMAR",
      "motor_modelo": "4TNV88-BGPGE",
      "motor_serie": "166249",
      "generador_marca": "MECCALTE",
      "generador_modelo": "ESE26YW",
      "combustible_lts": 100.0,
      "anticongelante_lts": 9.0,
      "aceite_lts": 12.0,
      "dimensiones_caseta": "LARGO DE CASETA 160CM , ANCHO DE CASETA  86CM. , ALTO DE CASETA  105 CM",
      "cantidad_ejes": 1.0,
      "modelo_llanta": "ST235/80R16",
      "amp_max": 50.0,
      "selector_volt": "MANUAL",
      "n_serie_equipo": "PEE2678680",
      "horometro": 1793.3
    }
  },
  {
    "tipo": "Generador",
    "marca": "Generac",
    "modelo": "P1603737",
    "cap_valor": 15.0,
    "cap_unidad": "KW",
    "voltaje": "220V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": true,
    "cambio_frecuencia": true,
    "economico": 7,
    "ficha": {
      "motor_marca": "PERKINS",
      "motor_modelo": "TYPE GK65596V",
      "motor_serie": "581131B",
      "generador_marca": "LEROY SOMAR",
      "generador_modelo": "LSA40SB J6/4",
      "combustible_lts": 180.0,
      "anticongelante_lts": 7.5,
      "aceite_lts": 10.0,
      "dimensiones_caseta": "LARGO 190cm -ANCHO 90 cm , ALTO 125cm",
      "peso_kg": 750.0,
      "cantidad_ejes": 1.0,
      "modelo_llanta": "215/70R16",
      "selector_volt": "MANUAL",
      "n_serie_equipo": "P16-03737",
      "horometro": 914.54
    }
  },
  {
    "tipo": "Compresor",
    "marca": "Kaeser",
    "modelo": "M150",
    "cap_valor": 375.0,
    "cap_unidad": "CFM",
    "voltaje": "175PSIG",
    "frecuencia": "1500Rpm",
    "traslado": "Grua",
    "cambio_voltaje": false,
    "cambio_frecuencia": false,
    "economico": 15,
    "ficha": {
      "motor_marca": "DEUTZ",
      "motor_modelo": "TCD2012 L04 2V",
      "motor_serie": "12268071",
      "combustible_lts": 200.0,
      "anticongelante_lts": 15.0,
      "aceite_lts": 19.0,
      "dimensiones_caseta": "MISMAS DEL REMOLQUE",
      "peso_kg": 2800.0,
      "cantidad_ejes": 1.0,
      "modelo_llanta": "195R14 TR603",
      "n_serie_equipo": "147618871610",
      "horometro": 975.18,
      "observaciones": "COMPRESOR DE AIRE"
    }
  },
  {
    "tipo": "Compresor",
    "marca": "Kaeser",
    "modelo": "M100",
    "cap_valor": 350.0,
    "cap_unidad": "CFM",
    "voltaje": "100PSI",
    "frecuencia": "1500Rpm",
    "traslado": "Grua",
    "cambio_voltaje": false,
    "cambio_frecuencia": false,
    "economico": 24,
    "ficha": {
      "motor_marca": "KUBOTA",
      "motor_modelo": "V3800-T",
      "motor_serie": "2NA1113",
      "combustible_lts": 150.0,
      "anticongelante_lts": 25.0,
      "aceite_lts": 12.0,
      "dimensiones_caseta": "es caseta y remolque juntos",
      "cantidad_ejes": 1.0,
      "modelo_llanta": "185r14c 102/1005",
      "n_serie_equipo": "1363-9283476",
      "horometro": 241.0
    }
  },
  {
    "tipo": "Compresor",
    "marca": "Kaeser",
    "modelo": "M50",
    "cap_valor": 185.0,
    "cap_unidad": "CFM",
    "voltaje": "100PSI",
    "frecuencia": "1500Rpm",
    "traslado": "Grua",
    "cambio_voltaje": false,
    "cambio_frecuencia": false,
    "economico": 26,
    "ficha": {
      "motor_marca": "KUBOTA",
      "motor_modelo": "V1505-T",
      "motor_serie": "1NW6200",
      "combustible_lts": 70.0,
      "anticongelante_lts": 10.0,
      "aceite_lts": 6.0,
      "dimensiones_caseta": "es caseta y remolque juntos",
      "peso_kg": 1500.0,
      "modelo_llanta": "145/80R13",
      "n_serie_equipo": "1394-9255763"
    }
  },
  {
    "tipo": "Torre de Iluminación",
    "marca": "Magnum",
    "modelo": "Torre de Luz 1076",
    "cap_valor": 6.0,
    "cap_unidad": "KW",
    "voltaje": "110V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": false,
    "cambio_frecuencia": false,
    "economico": 49,
    "ficha": {
      "motor_marca": "KUBOTA",
      "motor_modelo": "D1005 BGEF02",
      "motor_serie": "IJ935 21000",
      "generador_marca": "PANCAKE",
      "generador_modelo": "201CSA5411",
      "combustible_lts": 200.0,
      "anticongelante_lts": 3.0,
      "aceite_lts": 5.0,
      "dimensiones_caseta": "torre de iluminacion con luminarias ALTO  280CM",
      "cantidad_ejes": 1.0,
      "modelo_llanta": "ST175/80R13",
      "amp_max": 25.0,
      "n_serie_equipo": "3002841076",
      "horometro": 17333.0,
      "observaciones": "TORRE DE ILUMINACION CON REMOLQUE INCLUIDO 4 LAMPARAS DE ADITIVO METALICO"
    }
  },
  {
    "tipo": "Torre de Iluminación",
    "marca": "Magnum",
    "modelo": "Torre de Luz 3224",
    "cap_valor": 6.0,
    "cap_unidad": "KW",
    "voltaje": "110V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": false,
    "cambio_frecuencia": false,
    "economico": 50,
    "ficha": {
      "motor_marca": "KUBOTA",
      "motor_modelo": "D1005 BGEF02",
      "motor_serie": "1HA1828",
      "generador_marca": "PANCAKE",
      "generador_modelo": "201CSA5411",
      "combustible_lts": 200.0,
      "anticongelante_lts": 3.0,
      "aceite_lts": 5.0,
      "dimensiones_caseta": "torre de iluminacion con luminarias ALTO  280CM",
      "cantidad_ejes": 1.0,
      "modelo_llanta": "ST175/80R13",
      "amp_max": 25.0,
      "n_serie_equipo": "300185324",
      "horometro": 14733.0,
      "observaciones": "TORRE DE ILUMINACION CON REMOLQUE INCLUIDO 4 LAMPARAS DE ADITIVO METALICO"
    }
  },
  {
    "tipo": "Torre de Iluminación",
    "marca": "Magnum",
    "modelo": "MLT3060K",
    "cap_valor": 6.0,
    "cap_unidad": "KW",
    "voltaje": "110V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": false,
    "cambio_frecuencia": false,
    "economico": 69,
    "ficha": {
      "motor_marca": "KUBOTA",
      "motor_modelo": "D1005-BG-EF02",
      "motor_serie": "DKBXLO1.0BCC",
      "generador_marca": "MARATHON",
      "generador_modelo": "201CSA5411",
      "combustible_lts": 114.0,
      "anticongelante_lts": 5.0,
      "aceite_lts": 6.0,
      "peso_kg": 900.0,
      "cantidad_ejes": 1.0,
      "modelo_llanta": "ST/75/80R13",
      "amp_max": 15.0,
      "n_serie_equipo": "1306082",
      "horometro": 5599.0,
      "observaciones": "TORRE EN REPARACION"
    }
  },
  {
    "tipo": "Torre de Iluminación",
    "marca": "Generac",
    "modelo": "VT evo",
    "cap_valor": 4.2,
    "cap_unidad": "KVA",
    "voltaje": "110V",
    "frecuencia": "60Hz",
    "traslado": "Grua",
    "cambio_voltaje": false,
    "cambio_frecuencia": false,
    "economico": 36,
    "ficha": {
      "motor_marca": "KUBOTA",
      "motor_modelo": "Z482",
      "motor_serie": "4PHA327",
      "generador_marca": "LINZ",
      "combustible_lts": 120.0,
      "anticongelante_lts": 5.0,
      "aceite_lts": 3.0,
      "dimensiones_caseta": "torre de iluminacion con luminarias ALTO  265CM",
      "peso_kg": 750.0,
      "modelo_llanta": "165/70R13",
      "amp_max": 15.0,
      "n_serie_equipo": "HG10001943",
      "horometro": 257.0,
      "observaciones": "TORRE DE ILUMINACION SOLO TRASLADO EN GRUA"
    }
  },
  {
    "tipo": "Torre de Iluminación",
    "marca": "Generac",
    "modelo": "VT evo",
    "cap_valor": 4.2,
    "cap_unidad": "KVA",
    "voltaje": "110V",
    "frecuencia": "60Hz",
    "traslado": "Grua",
    "cambio_voltaje": false,
    "cambio_frecuencia": false,
    "economico": 36,
    "ficha": {
      "motor_marca": "KUBOTA",
      "motor_modelo": "Z482",
      "motor_serie": "4PHA327",
      "generador_marca": "LINZ",
      "combustible_lts": 120.0,
      "anticongelante_lts": 5.0,
      "aceite_lts": 3.0,
      "dimensiones_caseta": "torre de iluminacion con luminarias ALTO  265CM",
      "peso_kg": 750.0,
      "modelo_llanta": "165/70R13",
      "amp_max": 15.0,
      "n_serie_equipo": "HG10001943",
      "horometro": 257.0,
      "observaciones": "TORRE DE ILUMINACION SOLO TRASLADO EN GRUA"
    }
  },
  {
    "tipo": "Torre de Iluminación",
    "marca": "Generac",
    "modelo": "VT evo",
    "cap_valor": 4.2,
    "cap_unidad": "KVA",
    "voltaje": "110V",
    "frecuencia": "60Hz",
    "traslado": "Grua",
    "cambio_voltaje": false,
    "cambio_frecuencia": false,
    "economico": 36,
    "ficha": {
      "motor_marca": "KUBOTA",
      "motor_modelo": "Z482",
      "motor_serie": "4PHA327",
      "generador_marca": "LINZ",
      "combustible_lts": 120.0,
      "anticongelante_lts": 5.0,
      "aceite_lts": 3.0,
      "dimensiones_caseta": "torre de iluminacion con luminarias ALTO  265CM",
      "peso_kg": 750.0,
      "modelo_llanta": "165/70R13",
      "amp_max": 15.0,
      "n_serie_equipo": "HG10001943",
      "horometro": 257.0,
      "observaciones": "TORRE DE ILUMINACION SOLO TRASLADO EN GRUA"
    }
  },
  {
    "tipo": "Torre de Iluminación",
    "marca": "Generac",
    "modelo": "VT evo",
    "cap_valor": 4.2,
    "cap_unidad": "KVA",
    "voltaje": "110V",
    "frecuencia": "60Hz",
    "traslado": "Grúa",
    "cambio_voltaje": false,
    "cambio_frecuencia": false,
    "economico": 36,
    "ficha": {
      "motor_marca": "KUBOTA",
      "motor_modelo": "Z482",
      "motor_serie": "4PHA327",
      "generador_marca": "LINZ",
      "combustible_lts": 120.0,
      "anticongelante_lts": 5.0,
      "aceite_lts": 3.0,
      "dimensiones_caseta": "torre de iluminacion con luminarias ALTO  265CM",
      "peso_kg": 750.0,
      "modelo_llanta": "165/70R13",
      "amp_max": 15.0,
      "n_serie_equipo": "HG10001943",
      "horometro": 257.0,
      "observaciones": "TORRE DE ILUMINACION SOLO TRASLADO EN GRUA"
    }
  },
  {
    "tipo": "Torre de Iluminación",
    "marca": "Generac",
    "modelo": "VT evo",
    "cap_valor": 4.2,
    "cap_unidad": "KVA",
    "voltaje": "110V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": false,
    "cambio_frecuencia": false,
    "economico": 36,
    "ficha": {
      "motor_marca": "KUBOTA",
      "motor_modelo": "Z482",
      "motor_serie": "4PHA327",
      "generador_marca": "LINZ",
      "combustible_lts": 120.0,
      "anticongelante_lts": 5.0,
      "aceite_lts": 3.0,
      "dimensiones_caseta": "torre de iluminacion con luminarias ALTO  265CM",
      "peso_kg": 750.0,
      "modelo_llanta": "165/70R13",
      "amp_max": 15.0,
      "n_serie_equipo": "HG10001943",
      "horometro": 257.0,
      "observaciones": "TORRE DE ILUMINACION SOLO TRASLADO EN GRUA"
    }
  },
  {
    "tipo": "Torre de Iluminación",
    "marca": "Generac",
    "modelo": "1948",
    "cap_valor": 4.2,
    "cap_unidad": "KVA",
    "voltaje": "110V",
    "frecuencia": "60HZ",
    "traslado": "Grua",
    "cambio_voltaje": false,
    "cambio_frecuencia": false,
    "economico": 37,
    "ficha": {
      "motor_marca": "KUBOTA",
      "motor_modelo": "Z482",
      "motor_serie": "4PGS248",
      "generador_marca": "LINZ",
      "combustible_lts": 120.0,
      "anticongelante_lts": 4.0,
      "aceite_lts": 3.0,
      "dimensiones_caseta": "torre de iluminacion con luminarias ALTO  280CM",
      "cantidad_ejes": 1.0,
      "modelo_llanta": "165/70R13",
      "amp_max": 15.0,
      "n_serie_equipo": "HG10001948",
      "horometro": 174.0,
      "observaciones": "TORRE DE ILUMINACION SOLO TRASLADO EN GRUA"
    }
  },
  {
    "tipo": "Torre de Iluminación",
    "marca": "Generac",
    "modelo": "Torre de Luz 1954",
    "cap_valor": 4.2,
    "cap_unidad": "KVA",
    "voltaje": "110V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": false,
    "cambio_frecuencia": false,
    "economico": 38,
    "ficha": {
      "motor_marca": "KUBOTA",
      "motor_modelo": "Z482",
      "motor_serie": "4PHA317",
      "generador_marca": "LINZ",
      "combustible_lts": 120.0,
      "anticongelante_lts": 4.0,
      "aceite_lts": 3.0,
      "dimensiones_caseta": "torre de iluminacion con luminarias ALTO  280CM",
      "cantidad_ejes": 1.0,
      "modelo_llanta": "165/70R13",
      "amp_max": 15.0,
      "n_serie_equipo": "HG10001954",
      "horometro": 12.07,
      "observaciones": "TORRE DE ILUMINACION PARA TRASLADO EN ARRASTRE"
    }
  },
  {
    "tipo": "Torre de Iluminación",
    "marca": "Generac",
    "modelo": "Torre de Luz 2567",
    "cap_valor": 4.2,
    "cap_unidad": "KVA",
    "voltaje": "110V",
    "frecuencia": "60Hz",
    "traslado": "Grua",
    "cambio_voltaje": false,
    "cambio_frecuencia": false,
    "economico": 52,
    "ficha": {
      "motor_marca": "KUBOTA",
      "motor_modelo": "Z482-D2-EF07E",
      "motor_serie": "4NZ9438",
      "combustible_lts": 120.0,
      "anticongelante_lts": 5.0,
      "aceite_lts": 3.0,
      "dimensiones_caseta": "alto 265cm",
      "cantidad_ejes": 1.0,
      "modelo_llanta": "165/70r13",
      "amp_max": 15.0,
      "n_serie_equipo": "HG10002567",
      "observaciones": "torre de iluminacion  generac"
    }
  },
  {
    "tipo": "Torre de Iluminación",
    "marca": "Generac",
    "modelo": "Torre De Luz 2571",
    "cap_valor": 4.2,
    "cap_unidad": "KVA",
    "voltaje": "110V",
    "frecuencia": "60Hz",
    "traslado": "Grua",
    "cambio_voltaje": false,
    "cambio_frecuencia": false,
    "economico": 53,
    "ficha": {
      "motor_marca": "KUBOTA",
      "motor_modelo": "Z482-D2-EF07E",
      "motor_serie": "4NZ9394",
      "combustible_lts": 120.0,
      "anticongelante_lts": 5.0,
      "aceite_lts": 3.0,
      "dimensiones_caseta": "alto 265cm",
      "cantidad_ejes": 1.0,
      "modelo_llanta": "165/70r13",
      "amp_max": 15.0,
      "n_serie_equipo": "HG10002571",
      "observaciones": "torre de iluminacion  generac"
    }
  },
  {
    "tipo": "Torre de Iluminación",
    "marca": "Generac",
    "modelo": "Torre de Luz 2576",
    "cap_valor": 4.2,
    "cap_unidad": "KVA",
    "voltaje": "110V",
    "frecuencia": "60Hz",
    "traslado": "Grua",
    "cambio_voltaje": false,
    "cambio_frecuencia": false,
    "economico": 54,
    "ficha": {
      "motor_marca": "KUBOTA",
      "motor_modelo": "Z482-D2-EF07E",
      "motor_serie": "4NZ 9371",
      "combustible_lts": 120.0,
      "anticongelante_lts": 5.0,
      "aceite_lts": 3.0,
      "dimensiones_caseta": "alto 265cm",
      "cantidad_ejes": 1.0,
      "modelo_llanta": "165/70r13",
      "amp_max": 15.0,
      "n_serie_equipo": "HG10002576",
      "horometro": 7.0,
      "observaciones": "torre de iluminacion  generac"
    }
  },
  {
    "tipo": "Torre de Iluminación",
    "marca": "Generac",
    "modelo": "Torre de Luz 2570",
    "cap_valor": 4.2,
    "cap_unidad": "KVA",
    "voltaje": "110V",
    "frecuencia": "60Hz",
    "traslado": "Grua",
    "cambio_voltaje": false,
    "cambio_frecuencia": false,
    "economico": 55,
    "ficha": {
      "motor_marca": "KUBOTA",
      "motor_modelo": "Z482-D2-EF07E",
      "motor_serie": "4NZ-9435",
      "combustible_lts": 120.0,
      "anticongelante_lts": 5.0,
      "aceite_lts": 3.0,
      "dimensiones_caseta": "alto 265cm",
      "cantidad_ejes": 1.0,
      "modelo_llanta": "165/70r13",
      "amp_max": 15.0,
      "n_serie_equipo": "HG10002570",
      "horometro": 6.0,
      "observaciones": "torre de iluminacion  generac"
    }
  },
  {
    "tipo": "Torre de Iluminación",
    "marca": "Generac",
    "modelo": "Torre de Luz 2568",
    "cap_valor": 4.2,
    "cap_unidad": "KVA",
    "voltaje": "110V",
    "frecuencia": "60Hz",
    "traslado": "Grua",
    "cambio_voltaje": false,
    "cambio_frecuencia": false,
    "economico": 56,
    "ficha": {
      "motor_marca": "KUBOTA",
      "motor_modelo": "Z482-D2-EF07E",
      "motor_serie": "4NZ-9431",
      "combustible_lts": 120.0,
      "anticongelante_lts": 5.0,
      "aceite_lts": 3.0,
      "dimensiones_caseta": "alto 265cm",
      "cantidad_ejes": 1.0,
      "modelo_llanta": "165/70r13",
      "amp_max": 15.0,
      "n_serie_equipo": "HG10002568",
      "horometro": 7.2,
      "observaciones": "torre de iluminacion  generac"
    }
  },
  {
    "tipo": "Torre de Iluminación",
    "marca": "Generac",
    "modelo": "Torre de Luz 0827",
    "cap_valor": 4.2,
    "cap_unidad": "KVA",
    "voltaje": "110V",
    "frecuencia": "60Hz",
    "traslado": "Remolque",
    "cambio_voltaje": false,
    "cambio_frecuencia": false,
    "economico": 57,
    "ficha": {
      "motor_marca": "KUBOTA",
      "motor_modelo": "1E624-00000",
      "motor_serie": "4PH-4310",
      "combustible_lts": 120.0,
      "anticongelante_lts": 5.0,
      "aceite_lts": 3.0,
      "dimensiones_caseta": "alto 265cm",
      "cantidad_ejes": 1.0,
      "modelo_llanta": "165/70r13",
      "amp_max": 15.0,
      "n_serie_equipo": "HG1000827",
      "horometro": 7.0,
      "observaciones": "torre de iluminacion  generac"
    }
  }
];
